package com.qm.domain.entity;

import java.util.Date;

import com.qm.common.domain.BaseBean;

public class BusinessLog extends BaseBean{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_log.BusinessFlowNum
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    private Long businessFlowNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_log.UserID
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    private String userID;
    
    private String userLog;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_log.OperatorTime
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    private Date operatorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_log.RemoteIP
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    private String remoteIP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_log.URL
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    private String URL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_log.AccessParams
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    private String accessParams;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_log.BusinessFlowNum
     *
     * @return the value of business_log.BusinessFlowNum
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    public Long getBusinessFlowNum() {
        return businessFlowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_log.BusinessFlowNum
     *
     * @param businessFlowNum the value for business_log.BusinessFlowNum
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    public void setBusinessFlowNum(Long businessFlowNum) {
        this.businessFlowNum = businessFlowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_log.UserID
     *
     * @return the value of business_log.UserID
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    public String getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_log.UserID
     *
     * @param userID the value for business_log.UserID
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    public void setUserID(String userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_log.OperatorTime
     *
     * @return the value of business_log.OperatorTime
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_log.OperatorTime
     *
     * @param operatorTime the value for business_log.OperatorTime
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_log.RemoteIP
     *
     * @return the value of business_log.RemoteIP
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    public String getRemoteIP() {
        return remoteIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_log.RemoteIP
     *
     * @param remoteIP the value for business_log.RemoteIP
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    public void setRemoteIP(String remoteIP) {
        this.remoteIP = remoteIP == null ? null : remoteIP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_log.URL
     *
     * @return the value of business_log.URL
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    public String getURL() {
        return URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_log.URL
     *
     * @param URL the value for business_log.URL
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    public void setURL(String URL) {
        this.URL = URL == null ? null : URL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_log.AccessParams
     *
     * @return the value of business_log.AccessParams
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    public String getAccessParams() {
        return accessParams;
    }

    public String getUserLog() {
		return userLog;
	}

	public void setUserLog(String userLog) {
		this.userLog = userLog;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_log.AccessParams
     *
     * @param accessParams the value for business_log.AccessParams
     *
     * @mbggenerated Mon May 11 13:38:04 CST 2015
     */
    public void setAccessParams(String accessParams) {
        this.accessParams = accessParams == null ? null : accessParams.trim();
    }
}